default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: placemark_story_development

test:
  <<: *default
  database: placemark_story_test

production:
  <<: *default
  database: placemark_story_production
  username: placemark_story
  password: <%= ENV['PLACEMARK_STORY_DATABASE_PASSWORD'] %>
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
