# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default  
    mapbox_token: pk.eyJ1IjoibmJ1bWJhcmciLCJhIjoiN3piWUR1YyJ9.GlBZSAdYrbcHY_vzIrinvw

development:
  <<: *default
  secret_key_base: 56e198981f3e684363bcd1412162520fc7efbed7d05b9c87253cb50650ec147231ee154a7b7eee9d8fe84a6f912c5c7bc0353f599f16f1bc60e9128e81d32154

test:
  <<: *default
  secret_key_base: 8b3d45f81985248204b8dd189d91e6f4140f563c21d5e7cf8e0576872a53a2a03f9b6bae4834306bccadfac78c7353fa58453ba16d682161b3564b6e2ed95137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mapbox_token: <%= ENV['MAPBOX_KEY'] %>